name: automatic_version_upgrader
version: 0.1.0
publish_to: none
description: A command line interface to upgrade your app version automatically in a CI/CD flow.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  app_store_connect_api:
    path: packages/app_store_connect_api
  args: ^2.3.1
  equatable: ^2.0.3
  googleapis: ^9.1.0
  googleapis_auth: ^1.3.1
  http: ^0.13.5
  mason_logger: ^0.1.1
  meta: ^1.8.0
  pub_semver: ^2.1.1
  pub_updater: ^0.2.2
  pubspec: ^2.3.0
  universal_io: ^2.0.4
  usage: ^4.1.0

dev_dependencies:
  build_runner: ^2.2.0
  build_version: ^2.1.1
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

executables:
  automatic_version_upgrader:
