name: app_store_connect_api
description: A wrapper for the App Store Connect API.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto_keys: ^0.3.0
  dart_jsonwebtoken: ^2.4.2
  equatable: ^2.0.3
  http: ^0.13.5
  jose: ^0.3.2
  meta: ^1.8.0
  pub_semver: ^2.1.1
  universal_io: ^2.0.4

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1
