name: automatic_version_upgrader

on:
  pull_request:
    paths:
      - ".github/workflows/automatic_version_upgrader.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/automatic_version_upgrader.yaml"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: dart pub get

      - name: Format
        run: dart format --set-exit-if-changed .

      - name: Analyze
        run: dart analyze lib test

      - name: Verify Build
        run: dart run test --run-skipped -t pull-request-only

      - name: Run Tests
        run: |
          dart pub global activate coverage 1.2.0
          dart run test -j 1 -x pull-request-only -x e2e --coverage=coverage --test-randomize-ordering-seed random && dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib
      - name: Check Code Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0

  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: subosito/flutter-action@v1.5.3

      - name: Install LCOV
        run: sudo apt-get install -y lcov

      - name: Install Dependencies
        run: dart pub get

      - name: Run Tests
        run: dart run test --run-skipped -t e2e

  pana:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4

      - uses: subosito/flutter-action@v1.5.3

      - name: Install Dependencies
        run: |
          dart pub get
          dart pub global activate pana

      - name: Verify Pub Score
        run: |
          PANA=$(pana . --no-warning); PANA_SCORE=$(echo $PANA | sed -n "s/.*Points: \([0-9]*\)\/\([0-9]*\)./\1\/\2/p")
          echo "score: $PANA_SCORE"
          IFS='/'; read -a SCORE_ARR <<< "$PANA_SCORE"; SCORE=SCORE_ARR[0]; TOTAL=SCORE_ARR[1]
          if (( $SCORE < $TOTAL )); then echo "minimum score not met!"; exit 1; fi
